In [379]:
import pandas as pd
import numpy as np

In [380]:
df_tract=pd.read_excel('ZIP_TRACT_032015.xlsx',skipinitialspace=True)
df_age=pd.read_csv('age.csv',skipinitialspace=True)

In [381]:
print(df_tract.columns)
print(df_age.columns)

Index(['ZIP', 'TRACT', 'RES_RATIO', 'BUS_RATIO', 'OTH_RATIO', 'TOT_RATIO'], dtype='object')
Index(['TractID', 'Geography', 'Estimate; Total:', 'Estimate; Male:',
       'Estimate; Male: - 16 to 19 years:',
       'Estimate; Male: - 16 to 19 years: - In labor force:',
       'Estimate; Male: - 16 to 19 years: - In labor force: - In Armed Forces',
       'Estimate; Male: - 16 to 19 years: - In labor force: - Civilian:',
       'Estimate; Male: - 16 to 19 years: - In labor force: - Civilian: - Employed',
       'Estimate; Male: - 16 to 19 years: - In labor force: - Civilian: - Unemployed',
       ...
       'Estimate; Female: - 70 to 74 years:',
       'Estimate; Female: - 70 to 74 years: - In labor force:',
       'Estimate; Female: - 70 to 74 years: - In labor force: - Employed',
       'Estimate; Female: - 70 to 74 years: - In labor force: - Unemployed',
       'Estimate; Female: - 70 to 74 years: - Not in labor force',
       'Estimate; Female: - 75 years and over:',
       'Estimate; Female: - 75 years and over: - In labor force:',
       'Estimate; Female: - 75 years and over: - In labor force: - Employed',
       'Estimate; Female: - 75 years and over: - In labor force: - Unemployed',
       'Estimate; Female: - 75 years and over: - Not in labor force'],
      dtype='object', length=176)

In [382]:
df_age.head(2)

,TractID,Geography,Estimate; Total:,Estimate; Male:,Estimate; Male: - 16 to 19 years:,Estimate; Male: - 16 to 19 years: - In labor force:,Estimate; Male: - 16 to 19 years: - In labor force: - In Armed Forces,Estimate; Male: - 16 to 19 years: - In labor force: - Civilian:,Estimate; Male: - 16 to 19 years: - In labor force: - Civilian: - Employed,Estimate; Male: - 16 to 19 years: - In labor force: - Civilian: - Unemployed,...,Estimate; Female: - 70 to 74 years:,Estimate; Female: - 70 to 74 years: - In labor force:,Estimate; Female: - 70 to 74 years: - In labor force: - Employed,Estimate; Female: - 70 to 74 years: - In labor force: - Unemployed,Estimate; Female: - 70 to 74 years: - Not in labor force,Estimate; Female: - 75 years and over:,Estimate; Female: - 75 years and over: - In labor force:,Estimate; Female: - 75 years and over: - In labor force: - Employed,Estimate; Female: - 75 years and over: - In labor force: - Unemployed,Estimate; Female: - 75 years and over: - Not in labor force
0,6037101110,"Census Tract 1011.10, Los Angeles County, Cali...",3924,1925,110,6,0,6,6,0,...,67,6,6,0,61,168,0,0,0,168
1,6037101122,"Census Tract 1011.22, Los Angeles County, Cali...",2797,1407,28,0,0,0,0,0,...,65,48,30,18,17,64,6,6,0,58

In [383]:
df_tract.head(2)

   ZIP        TRACT  RES_RATIO  BUS_RATIO  OTH_RATIO  TOT_RATIO
0  501  36103158607   0.000000   1.000000   0.000000   1.000000
1  601  72001956700   0.831755   0.597297   0.657143   0.811885

In [384]:
df_tract.describe()

,ZIP,TRACT,RES_RATIO,BUS_RATIO,OTH_RATIO,TOT_RATIO
count,163289.000000,1.632890e+05,163289.000000,163289.000000,163289.000000,163289.000000
mean,49452.411369,2.893070e+10,0.206554,0.212666,0.210516,0.238418
std,28258.433760,1.601817e+10,0.295918,0.324044,0.334550,0.324313
min,501.000000,1.001020e+09,0.000000,0.000000,0.000000,0.000019
25%,27360.000000,1.604996e+10,0.014905,0.005455,0.000000,0.023021
50%,47525.000000,2.907700e+10,0.084985,0.052632,0.041667,0.094478
75%,74834.000000,4.201710e+10,0.219056,0.237398,0.223958,0.261237
max,99929.000000,7.803096e+10,1.000000,1.000000,1.000000,1.000000

In [385]:
df_age.describe()

,TractID,Estimate; Total:,Estimate; Male:,Estimate; Male: - 16 to 19 years:,Estimate; Male: - 16 to 19 years: - In labor force:,Estimate; Male: - 16 to 19 years: - In labor force: - In Armed Forces,Estimate; Male: - 16 to 19 years: - In labor force: - Civilian:,Estimate; Male: - 16 to 19 years: - In labor force: - Civilian: - Employed,Estimate; Male: - 16 to 19 years: - In labor force: - Civilian: - Unemployed,Estimate; Male: - 16 to 19 years: - Not in labor force,...,Estimate; Female: - 70 to 74 years:,Estimate; Female: - 70 to 74 years: - In labor force:,Estimate; Female: - 70 to 74 years: - In labor force: - Employed,Estimate; Female: - 70 to 74 years: - In labor force: - Unemployed,Estimate; Female: - 70 to 74 years: - Not in labor force,Estimate; Female: - 75 years and over:,Estimate; Female: - 75 years and over: - In labor force:,Estimate; Female: - 75 years and over: - In labor force: - Employed,Estimate; Female: - 75 years and over: - In labor force: - Unemployed,Estimate; Female: - 75 years and over: - Not in labor force
count,2.929000e+03,2929.000000,2929.000000,2929.000000,2929.000000,2929.000000,2929.000000,2929.000000,2929.000000,2929.000000,...,2929.000000,2929.000000,2929.000000,2929.000000,2929.000000,2929.000000,2929.000000,2929.000000,2929.000000,2929.000000
mean,6.041719e+09,3575.938546,1746.674974,128.874018,33.383066,0.046432,33.336634,21.333561,12.003073,95.490953,...,68.933424,9.889041,9.198020,0.691021,59.044384,145.100376,6.209628,5.860362,0.349266,138.890748
std,8.652155e+06,1391.756204,701.672447,116.553786,36.224540,1.021237,36.160399,26.858102,17.832200,92.884267,...,48.846349,14.608284,13.991595,3.411217,42.885961,112.584999,11.926278,11.670275,2.103187,108.150609
min,6.037101e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.037232e+09,2663.000000,1292.000000,67.000000,9.000000,0.000000,9.000000,0.000000,0.000000,45.000000,...,34.000000,0.000000,0.000000,0.000000,29.000000,71.000000,0.000000,0.000000,0.000000,69.000000
50%,6.037501e+09,3437.000000,1682.000000,113.000000,25.000000,0.000000,25.000000,14.000000,6.000000,82.000000,...,59.000000,5.000000,3.000000,0.000000,50.000000,122.000000,0.000000,0.000000,0.000000,117.000000
75%,6.037901e+09,4377.000000,2129.000000,170.000000,48.000000,0.000000,48.000000,31.000000,18.000000,126.000000,...,94.000000,15.000000,14.000000,0.000000,81.000000,192.000000,9.000000,8.000000,0.000000,182.000000
max,6.059990e+09,16439.000000,7668.000000,3394.000000,703.000000,32.000000,703.000000,526.000000,177.000000,2691.000000,...,395.000000,162.000000,162.000000,52.000000,343.000000,1623.000000,136.000000,136.000000,32.000000,1578.000000

In [386]:
df_tract.dtypes

ZIP            int64
TRACT          int64
RES_RATIO    float64
BUS_RATIO    float64
OTH_RATIO    float64
TOT_RATIO    float64
dtype: object

In [387]:
df_age.dtypes

TractID                                                                             int64
Geography                                                                          object
Estimate; Total:                                                                    int64
Estimate; Male:                                                                     int64
Estimate; Male: - 16 to 19 years:                                                   int64
Estimate; Male: - 16 to 19 years: - In labor force:                                 int64
Estimate; Male: - 16 to 19 years: - In labor force: - In Armed Forces               int64
Estimate; Male: - 16 to 19 years: - In labor force: - Civilian:                     int64
Estimate; Male: - 16 to 19 years: - In labor force: - Civilian: - Employed          int64
Estimate; Male: - 16 to 19 years: - In labor force: - Civilian: - Unemployed        int64
Estimate; Male: - 16 to 19 years: - Not in labor force                              int64
Estimate; Male: - 20 and 21 years:                                                  int64
Estimate; Male: - 20 and 21 years: - In labor force:                                int64
Estimate; Male: - 20 and 21 years: - In labor force: - In Armed Forces              int64
Estimate; Male: - 20 and 21 years: - In labor force: - Civilian:                    int64
Estimate; Male: - 20 and 21 years: - In labor force: - Civilian: - Employed         int64
Estimate; Male: - 20 and 21 years: - In labor force: - Civilian: - Unemployed       int64
Estimate; Male: - 20 and 21 years: - Not in labor force                             int64
Estimate; Male: - 22 to 24 years:                                                   int64
Estimate; Male: - 22 to 24 years: - In labor force:                                 int64
Estimate; Male: - 22 to 24 years: - In labor force: - In Armed Forces               int64
Estimate; Male: - 22 to 24 years: - In labor force: - Civilian:                     int64
Estimate; Male: - 22 to 24 years: - In labor force: - Civilian: - Employed          int64
Estimate; Male: - 22 to 24 years: - In labor force: - Civilian: - Unemployed        int64
Estimate; Male: - 22 to 24 years: - Not in labor force                              int64
Estimate; Male: - 25 to 29 years:                                                   int64
Estimate; Male: - 25 to 29 years: - In labor force:                                 int64
Estimate; Male: - 25 to 29 years: - In labor force: - In Armed Forces               int64
Estimate; Male: - 25 to 29 years: - In labor force: - Civilian:                     int64
Estimate; Male: - 25 to 29 years: - In labor force: - Civilian: - Employed          int64
                                                                                    ...
Estimate; Female: - 55 to 59 years: - Not in labor force                            int64
Estimate; Female: - 60 and 61 years:                                                int64
Estimate; Female: - 60 and 61 years: - In labor force:                              int64
Estimate; Female: - 60 and 61 years: - In labor force: - In Armed Forces            int64
Estimate; Female: - 60 and 61 years: - In labor force: - Civilian:                  int64
Estimate; Female: - 60 and 61 years: - In labor force: - Civilian: - Employed       int64
Estimate; Female: - 60 and 61 years: - In labor force: - Civilian: - Unemployed     int64
Estimate; Female: - 60 and 61 years: - Not in labor force                           int64
Estimate; Female: - 62 to 64 years:                                                 int64
Estimate; Female: - 62 to 64 years: - In labor force:                               int64
Estimate; Female: - 62 to 64 years: - In labor force: - In Armed Forces             int64
Estimate; Female: - 62 to 64 years: - In labor force: - Civilian:                   int64
Estimate; Female: - 62 to 64 years: - In labor force: - Civilian: - Employed        int64
Estimate; Female: - 62 to 64 years: - In labor force: - Civilian: - Unemployed      int64
Estimate; Female: - 62 to 64 years: - Not in labor force                            int64
Estimate; Female: - 65 to 69 years:                                                 int64
Estimate; Female: - 65 to 69 years: - In labor force:                               int64
Estimate; Female: - 65 to 69 years: - In labor force: - Employed                    int64
Estimate; Female: - 65 to 69 years: - In labor force: - Unemployed                  int64
Estimate; Female: - 65 to 69 years: - Not in labor force                            int64
Estimate; Female: - 70 to 74 years:                                                 int64
Estimate; Female: - 70 to 74 years: - In labor force:                               int64
Estimate; Female: - 70 to 74 years: - In labor force: - Employed                    int64
Estimate; Female: - 70 to 74 years: - In labor force: - Unemployed                  int64
Estimate; Female: - 70 to 74 years: - Not in labor force                            int64
Estimate; Female: - 75 years and over:                                              int64
Estimate; Female: - 75 years and over: - In labor force:                            int64
Estimate; Female: - 75 years and over: - In labor force: - Employed                 int64
Estimate; Female: - 75 years and over: - In labor force: - Unemployed               int64
Estimate; Female: - 75 years and over: - Not in labor force                         int64
dtype: object

In [388]:
df_age= df_age.rename(columns={'TractID': 'TRACT'})
df_age

,TRACT,Geography,Estimate; Total:,Estimate; Male:,Estimate; Male: - 16 to 19 years:,Estimate; Male: - 16 to 19 years: - In labor force:,Estimate; Male: - 16 to 19 years: - In labor force: - In Armed Forces,Estimate; Male: - 16 to 19 years: - In labor force: - Civilian:,Estimate; Male: - 16 to 19 years: - In labor force: - Civilian: - Employed,Estimate; Male: - 16 to 19 years: - In labor force: - Civilian: - Unemployed,...,Estimate; Female: - 70 to 74 years:,Estimate; Female: - 70 to 74 years: - In labor force:,Estimate; Female: - 70 to 74 years: - In labor force: - Employed,Estimate; Female: - 70 to 74 years: - In labor force: - Unemployed,Estimate; Female: - 70 to 74 years: - Not in labor force,Estimate; Female: - 75 years and over:,Estimate; Female: - 75 years and over: - In labor force:,Estimate; Female: - 75 years and over: - In labor force: - Employed,Estimate; Female: - 75 years and over: - In labor force: - Unemployed,Estimate; Female: - 75 years and over: - Not in labor force
0,6037101110,"Census Tract 1011.10, Los Angeles County, Cali...",3924,1925,110,6,0,6,6,0,...,67,6,6,0,61,168,0,0,0,168
1,6037101122,"Census Tract 1011.22, Los Angeles County, Cali...",2797,1407,28,0,0,0,0,0,...,65,48,30,18,17,64,6,6,0,58
2,6037101210,"Census Tract 1012.10, Los Angeles County, Cali...",4931,2541,175,44,0,44,23,21,...,55,0,0,0,55,117,0,0,0,117
3,6037101220,"Census Tract 1012.20, Los Angeles County, Cali...",2356,1055,18,7,0,7,7,0,...,40,16,16,0,24,125,0,0,0,125
4,6037101300,"Census Tract 1013, Los Angeles County, California",3856,1865,50,0,0,0,0,0,...,181,21,21,0,160,171,10,0,10,161
5,6037101400,"Census Tract 1014, Los Angeles County, California",3477,1679,112,15,0,15,9,6,...,68,8,8,0,60,160,46,46,0,114
6,6037102103,"Census Tract 1021.03, Los Angeles County, Cali...",1618,745,44,4,0,4,4,0,...,44,6,6,0,38,66,5,5,0,61
7,6037102104,"Census Tract 1021.04, Los Angeles County, Cali...",3116,1520,161,37,0,37,32,5,...,123,7,7,0,116,125,0,0,0,125
8,6037102105,"Census Tract 1021.05, Los Angeles County, Cali...",1597,841,91,53,0,53,34,19,...,17,7,7,0,10,25,0,0,0,25
9,6037102107,"Census Tract 1021.07, Los Angeles County, Cali...",3356,1790,128,42,0,42,14,28,...,59,0,0,0,59,257,0,0,0,257
10,6037103101,"Census Tract 1031.01, Los Angeles County, Cali...",2320,1232,64,4,0,4,4,0,...,42,0,0,0,42,105,0,0,0,105
11,6037103102,"Census Tract 1031.02, Los Angeles County, Cali...",4167,1796,142,17,0,17,8,9,...,86,9,0,9,77,171,12,12,0,159
12,6037103200,"Census Tract 1032, Los Angeles County, California",5431,3107,208,11,0,11,0,11,...,118,17,17,0,101,299,15,15,0,284
13,6037103300,"Census Tract 1033, Los Angeles County, California",2854,1355,48,13,0,13,7,6,...,98,10,10,0,88,96,0,0,0,96
14,6037103400,"Census Tract 1034, Los Angeles County, California",5661,2694,111,50,0,50,50,0,...,110,65,65,0,45,201,11,0,11,190
15,6037104103,"Census Tract 1041.03, Los Angeles County, Cali...",3148,1532,156,86,0,86,73,13,...,47,0,0,0,47,152,5,5,0,147
16,6037104105,"Census Tract 1041.05, Los Angeles County, Cali...",4322,2053,258,22,0,22,22,0,...,100,9,9,0,91,104,0,0,0,104
17,6037104108,"Census Tract 1041.08, Los Angeles County, Cali...",3844,1963,226,27,0,27,7,20,...,46,9,9,0,37,200,0,0,0,200
18,6037104124,"Census Tract 1041.24, Los Angeles County, Cali...",3604,1836,123,32,0,32,32,0,...,60,0,0,0,60,79,0,0,0,79
19,6037104201,"Census Tract 1042.01, Los Angeles County, Cali...",3627,1817,167,64,0,64,26,38,...,39,0,0,0,39,97,0,0,0,97
20,6037104203,"Census Tract 1042.03, Los Angeles County, Cali...",3504,1792,123,35,0,35,6,29,...,21,0,0,0,21,123,9,9,0,114
21,6037104204,"Census Tract 1042.04, Los Angeles County, Cali...",2719,1484,97,0,0,0,0,0,...,38,0,0,0,38,84,0,0,0,84
22,6037104310,"Census Tract 1043.10, Los Angeles County, Cali...",3888,1944,61,33,0,33,6,27,...,60,7,7,0,53,135,0,0,0,135
23,6037104320,"Census Tract 1043.20, Los Angeles County, Cali...",4324,2244,101,36,0,36,11,25,...,60,0,0,0,60,156,0,0,0,156
24,6037104401,"Census Tract 1044.01, Los Angeles County, Cali...",2694,1386,104,42,0,42,33,9,...,63,7,7,0,56,34,0,0,0,34
25,6037104403,"Census Tract 1044.03, Los Angeles County, Cali...",2320,1249,87,27,0,27,12,15,...,52,0,0,0,52,68,0,0,0,68
26,6037104404,"Census Tract 1044.04, Los Angeles County, Cali...",2021,1158,108,15,0,15,15,0,...,35,6,6,0,29,52,0,0,0,52
27,6037104500,"Census Tract 1045, Los Angeles County, California",2352,1235,150,81,0,81,51,30,...,14,0,0,0,14,61,6,6,0,55
28,6037104610,"Census Tract 1046.10, Los Angeles County, Cali...",2503,1311,75,19,0,19,19,0,...,29,0,0,0,29,90,0,0,0,90
29,6037104620,"Census Tract 1046.20, Los Angeles County, Cali...",2551,1373,132,86,0,86,49,37,...,47,0,0,0,47,70,0,0,0,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2899,6059110102,"Census Tract 1101.02, Orange County, California",4756,2268,130,5,0,5,5,0,...,51,16,16,0,35,247,17,17,0,230
2900,6059110104,"Census Tract 1101.04, Orange County, California",4506,2092,187,104,0,104,86,18,...,119,8,8,0,111,217,14,14,0,203
2901,6059110106,"Census Tract 1101.06, Orange County, California",3262,1461,65,17,0,17,17,0,...,87,36,36,0,51,177,7,7,0,170
2902,6059110108,"Census Tract 1101.08, Orange County, California",2393,1202,165,57,0,57,57,0,...,64,10,0,10,54,197,22,22,0,175
2903,6059110109,"Census Tract 1101.09, Orange County, California",4279,2123,134,16,0,16,16,0,...,96,22,22,0,74,176,8,8,0,168
2904,6059110110,"Census Tract 1101.10, Orange County, California",4598,2232,187,49,0,49,39,10,...,153,33,33,0,120,150,7,7,0,143
2905,6059110111,"Census Tract 1101.11, Orange County, California",4890,2436,130,0,0,0,0,0,...,63,16,16,0,47,236,8,8,0,228
2906,6059110113,"Census Tract 1101.13, Orange County, California",2050,999,92,36,0,36,30,6,...,61,0,0,0,61,116,8,8,0,108
2907,6059110114,"Census Tract 1101.14, Orange County, California",3794,1869,97,0,0,0,0,0,...,94,0,0,0,94,153,0,0,0,153
2908,6059110115,"Census Tract 1101.15, Orange County, California",2962,1407,89,6,0,6,0,6,...,104,9,9,0,95,212,0,0,0,212
2909,6059110116,"Census Tract 1101.16, Orange County, California",4070,1991,150,49,0,49,40,9,...,141,6,6,0,135,180,8,8,0,172
2910,6059110117,"Census Tract 1101.17, Orange County, California",4802,2315,214,19,0,19,0,19,...,58,0,0,0,58,228,0,0,0,228
2911,6059110118,"Census Tract 1101.18, Orange County, California",2209,1104,74,19,0,19,12,7,...,28,0,0,0,28,82,4,4,0,78
2912,6059110201,"Census Tract 1102.01, Orange County, California",6232,2994,219,30,0,30,30,0,...,143,0,0,0,143,398,0,0,0,398
2913,6059110202,"Census Tract 1102.02, Orange County, California",5890,2851,365,32,0,32,32,0,...,156,0,0,0,156,356,17,17,0,339
2914,6059110203,"Census Tract 1102.03, Orange County, California",4172,1995,193,115,0,115,115,0,...,58,10,10,0,48,122,0,0,0,122
2915,6059110301,"Census Tract 1103.01, Orange County, California",6052,2855,168,11,0,11,11,0,...,148,0,0,0,148,167,17,17,0,150
2916,6059110302,"Census Tract 1103.02, Orange County, California",4629,2241,198,26,0,26,4,22,...,77,13,13,0,64,115,0,0,0,115
2917,6059110303,"Census Tract 1103.03, Orange County, California",3987,2061,212,51,0,51,51,0,...,84,10,10,0,74,137,8,8,0,129
2918,6059110304,"Census Tract 1103.04, Orange County, California",3854,1904,147,43,0,43,43,0,...,99,16,16,0,83,161,11,11,0,150
2919,6059110401,"Census Tract 1104.01, Orange County, California",4267,2085,151,36,0,36,36,0,...,31,5,5,0,26,185,0,0,0,185
2920,6059110402,"Census Tract 1104.02, Orange County, California",4259,2063,233,70,0,70,61,9,...,84,0,0,0,84,179,0,0,0,179
2921,6059110500,"Census Tract 1105, Orange County, California",6190,3118,213,39,0,39,39,0,...,112,0,0,0,112,154,8,8,0,146
2922,6059110603,"Census Tract 1106.03, Orange County, California",6493,3036,184,91,0,91,78,13,...,58,5,5,0,53,193,0,0,0,193
2923,6059110604,"Census Tract 1106.04, Orange County, California",6739,3448,210,115,0,115,42,73,...,167,42,42,0,125,242,34,34,0,208
2924,6059110605,"Census Tract 1106.05, Orange County, California",5131,2193,215,40,0,40,0,40,...,78,0,0,0,78,331,11,11,0,320
2925,6059110606,"Census Tract 1106.06, Orange County, California",3443,1723,127,30,0,30,30,0,...,0,0,0,0,0,44,0,0,0,44
2926,6059110607,"Census Tract 1106.07, Orange County, California",3618,1767,43,8,0,8,8,0,...,34,0,0,0,34,163,9,9,0,154
2927,6059980000,"Census Tract 9800, Orange County, California",30,6,6,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2928,6059990100,"Census Tract 9901, Orange County, California",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [508]:
df_final=df_tract.merge(df_age,on='TRACT',how='inner')

In [509]:
df_final

,ZIP,TRACT,RES_RATIO,BUS_RATIO,OTH_RATIO,TOT_RATIO,Geography,Estimate; Total:,Estimate; Male:,Estimate; Male: - 16 to 19 years:,...,Estimate; Female: - 70 to 74 years:,Estimate; Female: - 70 to 74 years: - In labor force:,Estimate; Female: - 70 to 74 years: - In labor force: - Employed,Estimate; Female: - 70 to 74 years: - In labor force: - Unemployed,Estimate; Female: - 70 to 74 years: - Not in labor force,Estimate; Female: - 75 years and over:,Estimate; Female: - 75 years and over: - In labor force:,Estimate; Female: - 75 years and over: - In labor force: - Employed,Estimate; Female: - 75 years and over: - In labor force: - Unemployed,Estimate; Female: - 75 years and over: - Not in labor force
0,90001,6037535002,0.056005,0.075120,0.050633,0.057873,"Census Tract 5350.02, Los Angeles County, Cali...",2643,1453,253,...,37,0,0,0,37,48,0,0,0,48
1,90001,6037239330,0.047984,0.100962,0.020253,0.052840,"Census Tract 2393.30, Los Angeles County, Cali...",2255,1149,141,...,34,21,21,0,13,40,0,0,0,40
2,90003,6037239330,0.036595,0.046488,0.017102,0.036477,"Census Tract 2393.30, Los Angeles County, Cali...",2255,1149,141,...,34,21,21,0,13,40,0,0,0,40
3,90052,6037239330,0.000000,1.000000,1.000000,1.000000,"Census Tract 2393.30, Los Angeles County, Cali...",2255,1149,141,...,34,21,21,0,13,40,0,0,0,40
4,90059,6037239330,0.000000,0.006826,0.000000,0.000348,"Census Tract 2393.30, Los Angeles County, Cali...",2255,1149,141,...,34,21,21,0,13,40,0,0,0,40
5,90001,6037239802,0.056656,0.034856,0.101266,0.055482,"Census Tract 2398.02, Los Angeles County, Cali...",3416,1869,216,...,17,0,0,0,17,42,0,0,0,42
6,90003,6037239802,0.026715,0.024277,0.037804,0.027074,"Census Tract 2398.02, Los Angeles County, Cali...",3416,1869,216,...,17,0,0,0,17,42,0,0,0,42
7,90001,6037239502,0.047984,0.009615,0.015190,0.043153,"Census Tract 2395.02, Los Angeles County, Cali...",2453,1103,116,...,28,20,20,0,8,25,0,0,0,25
8,90003,6037239502,0.011923,0.005682,0.025203,0.012049,"Census Tract 2395.02, Los Angeles County, Cali...",2453,1103,116,...,28,20,20,0,8,25,0,0,0,25
9,90001,6037239801,0.040107,0.009014,0.035443,0.036736,"Census Tract 2398.01, Los Angeles County, Cali...",2294,1179,86,...,24,0,0,0,24,38,2,2,0,36
10,90003,6037239801,0.018436,0.013430,0.030603,0.018617,"Census Tract 2398.01, Los Angeles County, Cali...",2294,1179,86,...,24,0,0,0,24,38,2,2,0,36
11,90001,6037535102,0.013224,0.045673,0.020253,0.016796,"Census Tract 5351.02, Los Angeles County, Cali...",3487,1641,169,...,40,0,0,0,40,109,21,21,0,88
12,90002,6037535102,0.059284,0.033333,0.004255,0.056390,"Census Tract 5351.02, Los Angeles County, Cali...",3487,1641,169,...,40,0,0,0,40,109,21,21,0,88
13,90001,6037533002,0.043648,0.060096,0.005063,0.044411,"Census Tract 5330.02, Los Angeles County, Cali...",2014,1012,54,...,41,0,0,0,41,59,0,0,0,59
14,90001,6037532800,0.072409,0.055889,0.131646,0.072152,"Census Tract 5328, Los Angeles County, California",2788,1378,100,...,30,12,12,0,18,47,0,0,0,47
15,90011,6037532800,0.000000,0.009197,0.000000,0.000669,"Census Tract 5328, Los Angeles County, California",2788,1378,100,...,30,12,12,0,18,47,0,0,0,47
16,90001,6037239501,0.043359,0.031851,0.015190,0.041454,"Census Tract 2395.01, Los Angeles County, Cali...",2738,1422,157,...,22,0,0,0,22,62,7,7,0,55
17,90003,6037239501,0.015786,0.019628,0.016202,0.016160,"Census Tract 2395.01, Los Angeles County, Cali...",2738,1422,157,...,22,0,0,0,22,62,7,7,0,55
18,90001,6037239202,0.000072,0.098558,0.012658,0.010694,"Census Tract 2392.02, Los Angeles County, Cali...",3533,1667,243,...,58,0,0,0,58,32,0,0,0,32
19,90003,6037239202,0.061820,0.076963,0.043204,0.062228,"Census Tract 2392.02, Los Angeles County, Cali...",3533,1667,243,...,58,0,0,0,58,32,0,0,0,32
20,90011,6037239202,0.000000,0.027106,0.002351,0.002078,"Census Tract 2392.02, Los Angeles County, Cali...",3533,1667,243,...,58,0,0,0,58,32,0,0,0,32
21,90001,6037534900,0.086718,0.055889,0.050633,0.082594,"Census Tract 5349, Los Angeles County, California",4738,2594,218,...,52,23,23,0,29,117,0,0,0,117
22,90255,6037534900,0.010990,0.024722,0.006317,0.012204,"Census Tract 5349, Los Angeles County, California",4738,2594,218,...,52,23,23,0,29,117,0,0,0,117
23,90001,6037533001,0.076312,0.051683,0.096203,0.074228,"Census Tract 5330.01, Los Angeles County, Cali...",3189,1396,210,...,34,0,0,0,34,68,9,9,0,59
24,90001,6037535001,0.073421,0.042668,0.101266,0.070894,"Census Tract 5350.01, Los Angeles County, Cali...",3074,1462,156,...,69,0,0,0,69,86,0,0,0,86
25,90001,6037532900,0.109481,0.089543,0.144304,0.108259,"Census Tract 5329, Los Angeles County, California",4859,2605,264,...,50,0,0,0,50,55,11,5,6,44
26,90001,6037240010,0.000867,0.021635,0.005063,0.003145,"Census Tract 2400.10, Los Angeles County, Cali...",2461,1022,50,...,16,0,0,0,16,42,5,5,0,37
27,90002,6037240010,0.058736,0.053704,0.082979,0.059366,"Census Tract 2400.10, Los Angeles County, Cali...",2461,1022,50,...,16,0,0,0,16,42,5,5,0,37
28,90003,6037240010,0.012530,0.036674,0.026103,0.015451,"Census Tract 2400.10, Los Angeles County, Cali...",2461,1022,50,...,16,0,0,0,16,42,5,5,0,37
29,90001,6037532700,0.046755,0.090144,0.050633,0.051393,"Census Tract 5327, Los Angeles County, California",2164,1188,199,...,41,5,0,5,36,43,0,0,0,43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4932,93551,6037910201,0.043106,0.335030,0.305389,0.065771,"Census Tract 9102.01, Los Angeles County, Cali...",2858,1415,63,...,48,0,0,0,48,240,21,21,0,219
4933,93550,6037910502,0.053849,0.123524,0.098296,0.060488,"Census Tract 9105.02, Los Angeles County, Cali...",2947,1426,191,...,73,0,0,0,73,94,0,0,0,94
4934,93550,6037910601,0.073900,0.096457,0.064220,0.075355,"Census Tract 9106.01, Los Angeles County, Cali...",5008,2282,216,...,53,0,0,0,53,208,5,5,0,203
4935,93550,6037910603,0.088917,0.028543,0.026212,0.082466,"Census Tract 9106.03, Los Angeles County, Cali...",4965,2422,289,...,96,7,7,0,89,171,0,0,0,171
4936,93550,6037910605,0.058756,0.001476,0.005242,0.052809,"Census Tract 9106.05, Los Angeles County, Cali...",3247,1490,42,...,54,9,9,0,45,28,0,0,0,28
4937,93550,6037910711,0.008122,0.000492,0.000000,0.007301,"Census Tract 9107.11, Los Angeles County, Cali...",6348,3258,467,...,75,0,0,0,75,128,0,0,0,128
4938,93552,6037910711,0.223515,0.640187,0.615385,0.233160,"Census Tract 9107.11, Los Angeles County, Cali...",6348,3258,467,...,75,0,0,0,75,128,0,0,0,128
4939,93550,6037910504,0.053469,0.022146,0.005242,0.049669,"Census Tract 9105.04, Los Angeles County, Cali...",3262,1712,266,...,25,0,0,0,25,135,0,0,0,135
4940,93550,6037910403,0.029653,0.063976,0.065531,0.033327,"Census Tract 9104.03, Los Angeles County, Cali...",1444,674,80,...,4,0,0,0,4,15,0,0,0,15
4941,93551,6037910403,0.000000,0.002545,0.000000,0.000157,"Census Tract 9104.03, Los Angeles County, Cali...",1444,674,80,...,4,0,0,0,4,15,0,0,0,15
4942,93550,6037910101,0.011506,0.142717,0.039318,0.022395,"Census Tract 9101.01, Los Angeles County, Cali...",1195,653,55,...,0,0,0,0,0,0,0,0,0,0
4943,93552,6037910101,0.019385,0.004673,0.019231,0.019107,"Census Tract 9101.01, Los Angeles County, Cali...",1195,653,55,...,0,0,0,0,0,0,0,0,0,0
4944,93591,6037910101,0.006292,0.010417,0.041667,0.006823,"Census Tract 9101.01, Los Angeles County, Cali...",1195,653,55,...,0,0,0,0,0,0,0,0,0,0
4945,93550,6037910606,0.033460,0.005906,0.002621,0.030452,"Census Tract 9106.06, Los Angeles County, Cali...",2264,1057,120,...,16,6,6,0,10,53,0,0,0,53
4946,93550,6037910715,0.084010,0.006398,0.005242,0.075771,"Census Tract 9107.15, Los Angeles County, Cali...",4497,2053,204,...,47,9,0,9,38,81,0,0,0,81
4947,93550,6037980004,0.000465,0.007874,0.000000,0.001021,"Census Tract 9800.04, Los Angeles County, Cali...",11,11,0,...,0,0,0,0,0,0,0,0,0,0
4948,93552,6037980004,0.000451,0.000000,0.000000,0.000440,"Census Tract 9800.04, Los Angeles County, Cali...",11,11,0,...,0,0,0,0,0,0,0,0,0,0
4949,93599,6037980004,0.000000,0.000000,1.000000,1.000000,"Census Tract 9800.04, Los Angeles County, Cali...",11,11,0,...,0,0,0,0,0,0,0,0,0,0
4950,93550,6037910505,0.037563,0.001476,0.000000,0.033705,"Census Tract 9105.05, Los Angeles County, Cali...",2167,1009,146,...,42,0,0,0,42,74,18,18,0,56
4951,93551,6037910209,0.082164,0.042409,0.035928,0.078893,"Census Tract 9102.09, Los Angeles County, Cali...",3304,1527,104,...,105,0,0,0,105,79,0,0,0,79
4952,93551,6037910302,0.124416,0.016115,0.014970,0.115794,"Census Tract 9103.02, Los Angeles County, Cali...",4693,2198,268,...,109,15,15,0,94,278,15,15,0,263
4953,93551,6037910207,0.101893,0.003393,0.000000,0.094011,"Census Tract 9102.07, Los Angeles County, Cali...",4447,2183,240,...,117,0,0,0,117,117,0,0,0,117
4954,93551,6037910208,0.114722,0.194232,0.125749,0.119836,"Census Tract 9102.08, Los Angeles County, Cali...",4842,2322,164,...,124,0,0,0,124,125,16,16,0,109
4955,93551,6037910206,0.084673,0.000000,0.000000,0.077949,"Census Tract 9102.06, Los Angeles County, Cali...",2616,1259,99,...,29,0,0,0,29,43,0,0,0,43
4956,93551,6037910401,0.133653,0.175573,0.290419,0.138995,"Census Tract 9104.01, Los Angeles County, Cali...",5186,2578,195,...,103,0,0,0,103,177,11,11,0,166
4957,93551,6037910210,0.129376,0.004241,0.000000,0.119364,"Census Tract 9102.10, Los Angeles County, Cali...",5571,2668,492,...,66,0,0,0,66,144,0,0,0,144
4958,93552,6037910714,0.084483,0.060748,0.038462,0.083825,"Census Tract 9107.14, Los Angeles County, Cali...",2907,1428,218,...,34,4,4,0,30,80,4,4,0,76
4959,93552,6037910713,0.127851,0.070093,0.057692,0.126442,"Census Tract 9107.13, Los Angeles County, Cali...",4227,2222,155,...,62,0,0,0,62,96,0,0,0,96
4960,93552,6037910712,0.066991,0.093458,0.115385,0.067712,"Census Tract 9107.12, Los Angeles County, Cali...",1813,838,128,...,7,0,0,0,7,10,0,0,0,10
4961,93552,6037910705,0.288703,0.032710,0.038462,0.282733,"Census Tract 9107.05, Los Angeles County, Cali...",8950,4523,572,...,100,13,13,0,87,108,0,0,0,108

In [510]:
df_final.sort_values(by=['Geography','ZIP'],inplace=True)

In [511]:
df_final

,ZIP,TRACT,RES_RATIO,BUS_RATIO,OTH_RATIO,TOT_RATIO,Geography,Estimate; Total:,Estimate; Male:,Estimate; Male: - 16 to 19 years:,...,Estimate; Female: - 70 to 74 years:,Estimate; Female: - 70 to 74 years: - In labor force:,Estimate; Female: - 70 to 74 years: - In labor force: - Employed,Estimate; Female: - 70 to 74 years: - In labor force: - Unemployed,Estimate; Female: - 70 to 74 years: - Not in labor force,Estimate; Female: - 75 years and over:,Estimate; Female: - 75 years and over: - In labor force:,Estimate; Female: - 75 years and over: - In labor force: - Employed,Estimate; Female: - 75 years and over: - In labor force: - Unemployed,Estimate; Female: - 75 years and over: - Not in labor force
2621,91042,6037101110,0.165768,0.029907,0.185567,0.160449,"Census Tract 1011.10, Los Angeles County, Cali...",3924,1925,110,...,67,6,6,0,61,168,0,0,0,168
2620,91042,6037101122,0.131670,0.003738,0.000000,0.119054,"Census Tract 1011.22, Los Angeles County, Cali...",2797,1407,28,...,65,48,30,18,17,64,6,6,0,58
2617,91042,6037101210,0.222500,0.334579,0.474227,0.240456,"Census Tract 1012.10, Los Angeles County, Cali...",4931,2541,175,...,55,0,0,0,55,117,0,0,0,117
2618,91043,6037101210,1.000000,1.000000,1.000000,1.000000,"Census Tract 1012.10, Los Angeles County, Cali...",4931,2541,175,...,55,0,0,0,55,117,0,0,0,117
2619,91042,6037101220,0.128106,0.106542,0.195876,0.130533,"Census Tract 1012.20, Los Angeles County, Cali...",2356,1055,18,...,40,16,16,0,24,125,0,0,0,125
2622,91042,6037101300,0.134463,0.151402,0.013746,0.129142,"Census Tract 1013, Los Angeles County, California",3856,1865,50,...,181,21,21,0,160,171,10,0,10,161
2623,91214,6037101300,0.012201,0.002656,0.009634,0.011506,"Census Tract 1013, Los Angeles County, California",3856,1865,50,...,181,21,21,0,160,171,10,0,10,161
2608,91040,6037101400,0.005637,0.000000,0.000000,0.005276,"Census Tract 1014, Los Angeles County, California",3477,1679,112,...,68,8,8,0,60,160,46,46,0,114
2609,91042,6037101400,0.134849,0.289720,0.082474,0.139403,"Census Tract 1014, Los Angeles County, California",3477,1679,112,...,68,8,8,0,60,160,46,46,0,114
3180,91352,6037102103,0.058464,0.002684,0.016506,0.047195,"Census Tract 1021.03, Los Angeles County, Cali...",1618,745,44,...,44,6,6,0,38,66,5,5,0,61
3192,91352,6037102104,0.029639,0.000383,0.000000,0.023373,"Census Tract 1021.04, Los Angeles County, Cali...",3116,1520,161,...,123,7,7,0,116,125,0,0,0,125
3193,91504,6037102104,0.097702,0.034884,0.006483,0.088392,"Census Tract 1021.04, Los Angeles County, Cali...",3116,1520,161,...,123,7,7,0,116,125,0,0,0,125
3184,91352,6037102105,0.020275,0.004985,0.000000,0.016778,"Census Tract 1021.05, Los Angeles County, Cali...",1597,841,91,...,17,7,7,0,10,25,0,0,0,25
3185,91504,6037102105,0.013871,0.000000,0.000000,0.012158,"Census Tract 1021.05, Los Angeles County, Cali...",1597,841,91,...,17,7,7,0,10,25,0,0,0,25
3186,91505,6037102105,0.011710,0.003349,0.028935,0.011558,"Census Tract 1021.05, Los Angeles County, Cali...",1597,841,91,...,17,7,7,0,10,25,0,0,0,25
2604,91040,6037102107,0.043428,0.014045,0.000000,0.041252,"Census Tract 1021.07, Los Angeles County, Cali...",3356,1790,128,...,59,0,0,0,59,257,0,0,0,257
2605,91352,6037102107,0.077355,0.011503,0.057772,0.065446,"Census Tract 1021.07, Los Angeles County, Cali...",3356,1790,128,...,59,0,0,0,59,257,0,0,0,257
2595,91040,6037103101,0.096977,0.008427,0.000000,0.091138,"Census Tract 1031.01, Los Angeles County, Cali...",2320,1232,64,...,42,0,0,0,42,105,0,0,0,105
2596,91042,6037103101,0.019360,0.000000,0.000000,0.017480,"Census Tract 1031.01, Los Angeles County, Cali...",2320,1232,64,...,42,0,0,0,42,105,0,0,0,105
2610,91040,6037103102,0.178324,0.294944,0.180791,0.183355,"Census Tract 1031.02, Los Angeles County, Cali...",4167,1796,142,...,86,9,0,9,77,171,12,12,0,159
2611,91042,6037103102,0.029763,0.007477,0.008591,0.027655,"Census Tract 1031.02, Los Angeles County, Cali...",4167,1796,142,...,86,9,0,9,77,171,12,12,0,159
2612,91040,6037103200,0.207661,0.202247,0.186441,0.206979,"Census Tract 1032, Los Angeles County, California",5431,3107,208,...,118,17,17,0,101,299,15,15,0,284
2613,91041,6037103200,1.000000,1.000000,1.000000,1.000000,"Census Tract 1032, Los Angeles County, California",5431,3107,208,...,118,17,17,0,101,299,15,15,0,284
2614,91342,6037103200,0.026322,0.013699,0.002188,0.024822,"Census Tract 1032, Los Angeles County, California",5431,3107,208,...,118,17,17,0,101,299,15,15,0,284
2606,91040,6037103300,0.174737,0.089888,0.022599,0.167886,"Census Tract 1033, Los Angeles County, California",2854,1355,48,...,98,10,10,0,88,96,0,0,0,96
2607,91352,6037103300,0.005211,0.001150,0.000000,0.004290,"Census Tract 1033, Los Angeles County, California",2854,1355,48,...,98,10,10,0,88,96,0,0,0,96
2597,91040,6037103400,0.291827,0.390449,0.610169,0.302794,"Census Tract 1034, Los Angeles County, California",5661,2694,111,...,110,65,65,0,45,201,11,0,11,190
2598,91042,6037103400,0.023310,0.061682,0.034364,0.025654,"Census Tract 1034, Los Angeles County, California",5661,2694,111,...,110,65,65,0,45,201,11,0,11,190
3085,91342,6037104103,0.033431,0.002055,0.000000,0.030602,"Census Tract 1041.03, Los Angeles County, Cali...",3148,1532,156,...,47,0,0,0,47,152,5,5,0,147
3023,91331,6037104105,0.071347,0.020212,0.031941,0.065542,"Census Tract 1041.05, Los Angeles County, Cali...",4322,2053,258,...,100,9,9,0,91,104,0,0,0,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4171,92647,6059099602,0.027286,0.006291,0.000800,0.022737,"Census Tract 996.02, Orange County, California",2710,1268,118,...,60,0,0,0,60,175,0,0,0,175
4172,92683,6059099602,0.015269,0.033967,0.020245,0.017738,"Census Tract 996.02, Orange County, California",2710,1268,118,...,60,0,0,0,60,175,0,0,0,175
4181,92647,6059099603,0.019191,0.012583,0.002799,0.017053,"Census Tract 996.03, Orange County, California",5586,2654,179,...,121,43,43,0,78,314,0,0,0,314
4182,92649,6059099603,0.034256,0.635544,0.134436,0.103218,"Census Tract 996.03, Orange County, California",5586,2654,179,...,121,43,43,0,78,314,0,0,0,314
4183,92683,6059099603,0.049544,0.012674,0.009590,0.042994,"Census Tract 996.03, Orange County, California",5586,2654,179,...,121,43,43,0,78,314,0,0,0,314
4176,92647,6059099604,0.053135,0.009934,0.000800,0.043965,"Census Tract 996.04, Orange County, California",3064,1479,75,...,77,9,9,0,68,179,11,0,11,168
4177,92649,6059099604,0.000000,0.036605,0.001438,0.003847,"Census Tract 996.04, Orange County, California",3064,1479,75,...,77,9,9,0,68,179,11,0,11,168
3987,92605,6059099605,1.000000,1.000000,1.000000,1.000000,"Census Tract 996.05, Orange County, California",2974,1455,132,...,85,6,6,0,79,167,0,0,0,167
3988,92647,6059099605,0.101092,0.061258,0.015594,0.089368,"Census Tract 996.05, Orange County, California",2974,1455,132,...,85,6,6,0,79,167,0,0,0,167
4220,92655,6059099701,0.422895,0.271889,0.704348,0.431730,"Census Tract 997.01, Orange County, California",5324,2602,112,...,196,6,6,0,190,186,0,0,0,186
4221,92683,6059099701,0.014515,0.019518,0.003197,0.014470,"Census Tract 997.01, Orange County, California",5324,2602,112,...,196,6,6,0,190,186,0,0,0,186
4173,92647,6059099702,0.006832,0.000662,0.000000,0.005579,"Census Tract 997.02, Orange County, California",6787,3563,209,...,119,15,15,0,104,360,19,19,0,341
4174,92655,6059099702,0.532640,0.723502,0.295652,0.529022,"Census Tract 997.02, Orange County, California",6787,3563,209,...,119,15,15,0,104,360,19,19,0,341
4175,92683,6059099702,0.041173,0.029658,0.006393,0.037883,"Census Tract 997.02, Orange County, California",6787,3563,209,...,119,15,15,0,104,360,19,19,0,341
4178,92647,6059099703,0.012185,0.087417,0.013195,0.020246,"Census Tract 997.03, Orange County, California",4517,2356,144,...,89,51,51,0,38,166,12,12,0,154
4179,92655,6059099703,0.044465,0.004608,0.000000,0.039248,"Census Tract 997.03, Orange County, California",4517,2356,144,...,89,51,51,0,38,166,12,12,0,154
4180,92683,6059099703,0.045232,0.010900,0.012786,0.039399,"Census Tract 997.03, Orange County, California",4517,2356,144,...,89,51,51,0,38,166,12,12,0,154
4320,92683,6059099801,0.058561,0.054246,0.092701,0.059960,"Census Tract 998.01, Orange County, California",4888,2460,215,...,42,0,0,0,42,178,0,0,0,178
4321,92841,6059099801,0.000000,0.002179,0.000000,0.000259,"Census Tract 998.01, Orange County, California",4888,2460,215,...,42,0,0,0,42,178,0,0,0,178
4322,92844,6059099801,0.000000,0.001087,0.000000,0.000117,"Census Tract 998.01, Orange County, California",4888,2460,215,...,42,0,0,0,42,178,0,0,0,178
4327,92683,6059099802,0.070202,0.072750,0.135322,0.074132,"Census Tract 998.02, Orange County, California",4235,2004,122,...,122,8,8,0,114,300,8,8,0,292
4316,92683,6059099803,0.062118,0.042586,0.043687,0.058801,"Census Tract 998.03, Orange County, California",4480,2334,113,...,121,0,0,0,121,305,0,0,0,305
4309,92683,6059099902,0.047747,0.019011,0.019180,0.042786,"Census Tract 999.02, Orange County, California",3740,1752,161,...,30,16,16,0,14,162,0,0,0,162
4310,92683,6059099903,0.053388,0.029658,0.074054,0.051759,"Census Tract 999.03, Orange County, California",4738,2516,153,...,55,5,5,0,50,149,0,0,0,149
4311,92841,6059099903,0.000000,0.034858,0.002584,0.004315,"Census Tract 999.03, Orange County, California",4738,2516,153,...,55,5,5,0,50,149,0,0,0,149
4337,92683,6059099904,0.068549,0.039290,0.187533,0.071755,"Census Tract 999.04, Orange County, California",5389,2639,216,...,72,0,0,0,72,222,0,0,0,222
4338,92684,6059099904,1.000000,1.000000,1.000000,1.000000,"Census Tract 999.04, Orange County, California",5389,2639,216,...,72,0,0,0,72,222,0,0,0,222
4318,92683,6059099905,0.049220,0.013942,0.008524,0.042816,"Census Tract 999.05, Orange County, California",3505,1776,111,...,56,0,0,0,56,136,25,25,0,111
4319,92845,6059099905,0.000000,0.039683,0.005714,0.002537,"Census Tract 999.05, Orange County, California",3505,1776,111,...,56,0,0,0,56,136,25,25,0,111
4328,92683,6059099906,0.060070,0.010900,0.008524,0.051432,"Census Tract 999.06, Orange County, California",4042,1951,77,...,94,11,11,0,83,211,7,7,0,204

In [512]:
df_final.drop(labels=['TRACT','RES_RATIO','BUS_RATIO','OTH_RATIO','TOT_RATIO'],axis=1,inplace=True)

In [513]:
arr_variables=df_final.columns 
arr_variables.unique()

array(['ZIP', 'Geography', 'Estimate; Total:', 'Estimate; Male:',
       'Estimate; Male: - 16 to 19 years:',
       'Estimate; Male: - 16 to 19 years: - In labor force:',
       'Estimate; Male: - 16 to 19 years: - In labor force: - In Armed Forces',
       'Estimate; Male: - 16 to 19 years: - In labor force: - Civilian:',
       'Estimate; Male: - 16 to 19 years: - In labor force: - Civilian: - Employed',
       'Estimate; Male: - 16 to 19 years: - In labor force: - Civilian: - Unemployed',
       'Estimate; Male: - 16 to 19 years: - Not in labor force',
       'Estimate; Male: - 20 and 21 years:',
       'Estimate; Male: - 20 and 21 years: - In labor force:',
       'Estimate; Male: - 20 and 21 years: - In labor force: - In Armed Forces',
       'Estimate; Male: - 20 and 21 years: - In labor force: - Civilian:',
       'Estimate; Male: - 20 and 21 years: - In labor force: - Civilian: - Employed',
       'Estimate; Male: - 20 and 21 years: - In labor force: - Civilian: - Unemployed',
       'Estimate; Male: - 20 and 21 years: - Not in labor force',
       'Estimate; Male: - 22 to 24 years:',
       'Estimate; Male: - 22 to 24 years: - In labor force:',
       'Estimate; Male: - 22 to 24 years: - In labor force: - In Armed Forces',
       'Estimate; Male: - 22 to 24 years: - In labor force: - Civilian:',
       'Estimate; Male: - 22 to 24 years: - In labor force: - Civilian: - Employed',
       'Estimate; Male: - 22 to 24 years: - In labor force: - Civilian: - Unemployed',
       'Estimate; Male: - 22 to 24 years: - Not in labor force',
       'Estimate; Male: - 25 to 29 years:',
       'Estimate; Male: - 25 to 29 years: - In labor force:',
       'Estimate; Male: - 25 to 29 years: - In labor force: - In Armed Forces',
       'Estimate; Male: - 25 to 29 years: - In labor force: - Civilian:',
       'Estimate; Male: - 25 to 29 years: - In labor force: - Civilian: - Employed',
       'Estimate; Male: - 25 to 29 years: - In labor force: - Civilian: - Unemployed',
       'Estimate; Male: - 25 to 29 years: - Not in labor force',
       'Estimate; Male: - 30 to 34 years:',
       'Estimate; Male: - 30 to 34 years: - In labor force:',
       'Estimate; Male: - 30 to 34 years: - In labor force: - In Armed Forces',
       'Estimate; Male: - 30 to 34 years: - In labor force: - Civilian:',
       'Estimate; Male: - 30 to 34 years: - In labor force: - Civilian: - Employed',
       'Estimate; Male: - 30 to 34 years: - In labor force: - Civilian: - Unemployed',
       'Estimate; Male: - 30 to 34 years: - Not in labor force',
       'Estimate; Male: - 35 to 44 years:',
       'Estimate; Male: - 35 to 44 years: - In labor force:',
       'Estimate; Male: - 35 to 44 years: - In labor force: - In Armed Forces',
       'Estimate; Male: - 35 to 44 years: - In labor force: - Civilian:',
       'Estimate; Male: - 35 to 44 years: - In labor force: - Civilian: - Employed',
       'Estimate; Male: - 35 to 44 years: - In labor force: - Civilian: - Unemployed',
       'Estimate; Male: - 35 to 44 years: - Not in labor force',
       'Estimate; Male: - 45 to 54 years:',
       'Estimate; Male: - 45 to 54 years: - In labor force:',
       'Estimate; Male: - 45 to 54 years: - In labor force: - In Armed Forces',
       'Estimate; Male: - 45 to 54 years: - In labor force: - Civilian:',
       'Estimate; Male: - 45 to 54 years: - In labor force: - Civilian: - Employed',
       'Estimate; Male: - 45 to 54 years: - In labor force: - Civilian: - Unemployed',
       'Estimate; Male: - 45 to 54 years: - Not in labor force',
       'Estimate; Male: - 55 to 59 years:',
       'Estimate; Male: - 55 to 59 years: - In labor force:',
       'Estimate; Male: - 55 to 59 years: - In labor force: - In Armed Forces',
       'Estimate; Male: - 55 to 59 years: - In labor force: - Civilian:',
       'Estimate; Male: - 55 to 59 years: - In labor force: - Civilian: - Employed',
       'Estimate; Male: - 55 to 59 years: - In labor force: - Civilian: - Unemployed',
       'Estimate; Male: - 55 to 59 years: - Not in labor force',
       'Estimate; Male: - 60 and 61 years:',
       'Estimate; Male: - 60 and 61 years: - In labor force:',
       'Estimate; Male: - 60 and 61 years: - In labor force: - In Armed Forces',
       'Estimate; Male: - 60 and 61 years: - In labor force: - Civilian:',
       'Estimate; Male: - 60 and 61 years: - In labor force: - Civilian: - Employed',
       'Estimate; Male: - 60 and 61 years: - In labor force: - Civilian: - Unemployed',
       'Estimate; Male: - 60 and 61 years: - Not in labor force',
       'Estimate; Male: - 62 to 64 years:',
       'Estimate; Male: - 62 to 64 years: - In labor force:',
       'Estimate; Male: - 62 to 64 years: - In labor force: - In Armed Forces',
       'Estimate; Male: - 62 to 64 years: - In labor force: - Civilian:',
       'Estimate; Male: - 62 to 64 years: - In labor force: - Civilian: - Employed',
       'Estimate; Male: - 62 to 64 years: - In labor force: - Civilian: - Unemployed',
       'Estimate; Male: - 62 to 64 years: - Not in labor force',
       'Estimate; Male: - 65 to 69 years:',
       'Estimate; Male: - 65 to 69 years: - In labor force:',
       'Estimate; Male: - 65 to 69 years: - In labor force: - Employed',
       'Estimate; Male: - 65 to 69 years: - In labor force: - Unemployed',
       'Estimate; Male: - 65 to 69 years: - Not in labor force',
       'Estimate; Male: - 70 to 74 years:',
       'Estimate; Male: - 70 to 74 years: - In labor force:',
       'Estimate; Male: - 70 to 74 years: - In labor force: - Employed',
       'Estimate; Male: - 70 to 74 years: - In labor force: - Unemployed',
       'Margin of Error; Male: - 70 to 74 years: - In labor force: - Unemployed',
       'Estimate; Male: - 70 to 74 years: - Not in labor force',
       'Estimate; Male: - 75 years and over:',
       'Estimate; Male: - 75 years and over: - In labor force:',
       'Estimate; Male: - 75 years and over: - In labor force: - Employed',
       'Estimate; Male: - 75 years and over: - In labor force: - Unemployed',
       'Estimate; Male: - 75 years and over: - Not in labor force',
       'Estimate; Female:', 'Estimate; Female: - 16 to 19 years:',
       'Estimate; Female: - 16 to 19 years: - In labor force:',
       'Estimate; Female: - 16 to 19 years: - In labor force: - In Armed Forces',
       'Estimate; Female: - 16 to 19 years: - In labor force: - Civilian:',
       'Estimate; Female: - 16 to 19 years: - In labor force: - Civilian: - Employed',
       'Estimate; Female: - 16 to 19 years: - In labor force: - Civilian: - Unemployed',
       'Estimate; Female: - 16 to 19 years: - Not in labor force',
       'Estimate; Female: - 20 and 21 years:',
       'Estimate; Female: - 20 and 21 years: - In labor force:',
       'Estimate; Female: - 20 and 21 years: - In labor force: - In Armed Forces',
       'Estimate; Female: - 20 and 21 years: - In labor force: - Civilian:',
       'Estimate; Female: - 20 and 21 years: - In labor force: - Civilian: - Employed',
       'Estimate; Female: - 20 and 21 years: - In labor force: - Civilian: - Unemployed',
       'Estimate; Female: - 20 and 21 years: - Not in labor force',
       'Estimate; Female: - 22 to 24 years:',
       'Estimate; Female: - 22 to 24 years: - In labor force:',
       'Estimate; Female: - 22 to 24 years: - In labor force: - In Armed Forces',
       'Estimate; Female: - 22 to 24 years: - In labor force: - Civilian:',
       'Estimate; Female: - 22 to 24 years: - In labor force: - Civilian: - Employed',
       'Estimate; Female: - 22 to 24 years: - In labor force: - Civilian: - Unemployed',
       'Estimate; Female: - 22 to 24 years: - Not in labor force',
       'Estimate; Female: - 25 to 29 years:',
       'Estimate; Female: - 25 to 29 years: - In labor force:',
       'Estimate; Female: - 25 to 29 years: - In labor force: - In Armed Forces',
       'Estimate; Female: - 25 to 29 years: - In labor force: - Civilian:',
       'Estimate; Female: - 25 to 29 years: - In labor force: - Civilian: - Employed',
       'Estimate; Female: - 25 to 29 years: - In labor force: - Civilian: - Unemployed',
       'Estimate; Female: - 25 to 29 years: - Not in labor force',
       'Estimate; Female: - 30 to 34 years:',
       'Estimate; Female: - 30 to 34 years: - In labor force:',
       'Estimate; Female: - 30 to 34 years: - In labor force: - In Armed Forces',
       'Estimate; Female: - 30 to 34 years: - In labor force: - Civilian:',
       'Estimate; Female: - 30 to 34 years: - In labor force: - Civilian: - Employed',
       'Estimate; Female: - 30 to 34 years: - In labor force: - Civilian: - Unemployed',
       'Estimate; Female: - 30 to 34 years: - Not in labor force',
       'Estimate; Female: - 35 to 44 years:',
       'Estimate; Female: - 35 to 44 years: - In labor force:',
       'Estimate; Female: - 35 to 44 years: - In labor force: - In Armed Forces',
       'Estimate; Female: - 35 to 44 years: - In labor force: - Civilian:',
       'Estimate; Female: - 35 to 44 years: - In labor force: - Civilian: - Employed',
       'Estimate; Female: - 35 to 44 years: - In labor force: - Civilian: - Unemployed',
       'Estimate; Female: - 35 to 44 years: - Not in labor force',
       'Estimate; Female: - 45 to 54 years:',
       'Estimate; Female: - 45 to 54 years: - In labor force:',
       'Estimate; Female: - 45 to 54 years: - In labor force: - In Armed Forces',
       'Estimate; Female: - 45 to 54 years: - In labor force: - Civilian:',
       'Estimate; Female: - 45 to 54 years: - In labor force: - Civilian: - Employed',
       'Estimate; Female: - 45 to 54 years: - In labor force: - Civilian: - Unemployed',
       'Estimate; Female: - 45 to 54 years: - Not in labor force',
       'Estimate; Female: - 55 to 59 years:',
       'Estimate; Female: - 55 to 59 years: - In labor force:',
       'Estimate; Female: - 55 to 59 years: - In labor force: - In Armed Forces',
       'Estimate; Female: - 55 to 59 years: - In labor force: - Civilian:',
       'Estimate; Female: - 55 to 59 years: - In labor force: - Civilian: - Employed',
       'Estimate; Female: - 55 to 59 years: - In labor force: - Civilian: - Unemployed',
       'Estimate; Female: - 55 to 59 years: - Not in labor force',
       'Estimate; Female: - 60 and 61 years:',
       'Estimate; Female: - 60 and 61 years: - In labor force:',
       'Estimate; Female: - 60 and 61 years: - In labor force: - In Armed Forces',
       'Estimate; Female: - 60 and 61 years: - In labor force: - Civilian:',
       'Estimate; Female: - 60 and 61 years: - In labor force: - Civilian: - Employed',
       'Estimate; Female: - 60 and 61 years: - In labor force: - Civilian: - Unemployed',
       'Estimate; Female: - 60 and 61 years: - Not in labor force',
       'Estimate; Female: - 62 to 64 years:',
       'Estimate; Female: - 62 to 64 years: - In labor force:',
       'Estimate; Female: - 62 to 64 years: - In labor force: - In Armed Forces',
       'Estimate; Female: - 62 to 64 years: - In labor force: - Civilian:',
       'Estimate; Female: - 62 to 64 years: - In labor force: - Civilian: - Employed',
       'Estimate; Female: - 62 to 64 years: - In labor force: - Civilian: - Unemployed',
       'Estimate; Female: - 62 to 64 years: - Not in labor force',
       'Estimate; Female: - 65 to 69 years:',
       'Estimate; Female: - 65 to 69 years: - In labor force:',
       'Estimate; Female: - 65 to 69 years: - In labor force: - Employed',
       'Estimate; Female: - 65 to 69 years: - In labor force: - Unemployed',
       'Estimate; Female: - 65 to 69 years: - Not in labor force',
       'Estimate; Female: - 70 to 74 years:',
       'Estimate; Female: - 70 to 74 years: - In labor force:',
       'Estimate; Female: - 70 to 74 years: - In labor force: - Employed',
       'Estimate; Female: - 70 to 74 years: - In labor force: - Unemployed',
       'Estimate; Female: - 70 to 74 years: - Not in labor force',
       'Estimate; Female: - 75 years and over:',
       'Estimate; Female: - 75 years and over: - In labor force:',
       'Estimate; Female: - 75 years and over: - In labor force: - Employed',
       'Estimate; Female: - 75 years and over: - In labor force: - Unemployed',
       'Estimate; Female: - 75 years and over: - Not in labor force'], dtype=object)

In [514]:
variables=[]
for ss in arr_variables:
    if 'labor force' in ss:
        pass
    else:
        variables.append(ss)

In [515]:
variables

['ZIP',
 'Geography',
 'Estimate; Total:',
 'Estimate; Male:',
 'Estimate; Male: - 16 to 19 years:',
 'Estimate; Male: - 20 and 21 years:',
 'Estimate; Male: - 22 to 24 years:',
 'Estimate; Male: - 25 to 29 years:',
 'Estimate; Male: - 30 to 34 years:',
 'Estimate; Male: - 35 to 44 years:',
 'Estimate; Male: - 45 to 54 years:',
 'Estimate; Male: - 55 to 59 years:',
 'Estimate; Male: - 60 and 61 years:',
 'Estimate; Male: - 62 to 64 years:',
 'Estimate; Male: - 65 to 69 years:',
 'Estimate; Male: - 70 to 74 years:',
 'Estimate; Male: - 75 years and over:',
 'Estimate; Female:',
 'Estimate; Female: - 16 to 19 years:',
 'Estimate; Female: - 20 and 21 years:',
 'Estimate; Female: - 22 to 24 years:',
 'Estimate; Female: - 25 to 29 years:',
 'Estimate; Female: - 30 to 34 years:',
 'Estimate; Female: - 35 to 44 years:',
 'Estimate; Female: - 45 to 54 years:',
 'Estimate; Female: - 55 to 59 years:',
 'Estimate; Female: - 60 and 61 years:',
 'Estimate; Female: - 62 to 64 years:',
 'Estimate; Female: - 65 to 69 years:',
 'Estimate; Female: - 70 to 74 years:',
 'Estimate; Female: - 75 years and over:']

In [516]:
retain_variables=[]
for each in variables:
    if('ZIP' ==each or 'Geography' ==each or 'Estimate; Total:'== each or 'Estimate; Male:'==each or 'Estimate; Female:'== each or '65 to 69 years:' in each or '70 to 74 years:' in each or '75 years' in each):
        retain_variables.append(each)
    else:
        pass

In [517]:
retain_variables

['ZIP',
 'Geography',
 'Estimate; Total:',
 'Estimate; Male:',
 'Estimate; Male: - 65 to 69 years:',
 'Estimate; Male: - 70 to 74 years:',
 'Estimate; Male: - 75 years and over:',
 'Estimate; Female:',
 'Estimate; Female: - 65 to 69 years:',
 'Estimate; Female: - 70 to 74 years:',
 'Estimate; Female: - 75 years and over:']

In [518]:
df_final=df_final[retain_variables]

In [519]:
df_final

,ZIP,Geography,Estimate; Total:,Estimate; Male:,Estimate; Male: - 65 to 69 years:,Estimate; Male: - 70 to 74 years:,Estimate; Male: - 75 years and over:,Estimate; Female:,Estimate; Female: - 65 to 69 years:,Estimate; Female: - 70 to 74 years:,Estimate; Female: - 75 years and over:
2621,91042,"Census Tract 1011.10, Los Angeles County, Cali...",3924,1925,87,25,145,1999,156,67,168
2620,91042,"Census Tract 1011.22, Los Angeles County, Cali...",2797,1407,61,113,66,1390,140,65,64
2617,91042,"Census Tract 1012.10, Los Angeles County, Cali...",4931,2541,26,0,102,2390,215,55,117
2618,91043,"Census Tract 1012.10, Los Angeles County, Cali...",4931,2541,26,0,102,2390,215,55,117
2619,91042,"Census Tract 1012.20, Los Angeles County, Cali...",2356,1055,73,36,47,1301,22,40,125
2622,91042,"Census Tract 1013, Los Angeles County, California",3856,1865,106,134,170,1991,127,181,171
2623,91214,"Census Tract 1013, Los Angeles County, California",3856,1865,106,134,170,1991,127,181,171
2608,91040,"Census Tract 1014, Los Angeles County, California",3477,1679,84,90,56,1798,157,68,160
2609,91042,"Census Tract 1014, Los Angeles County, California",3477,1679,84,90,56,1798,157,68,160
3180,91352,"Census Tract 1021.03, Los Angeles County, Cali...",1618,745,67,37,60,873,33,44,66
3192,91352,"Census Tract 1021.04, Los Angeles County, Cali...",3116,1520,66,38,172,1596,109,123,125
3193,91504,"Census Tract 1021.04, Los Angeles County, Cali...",3116,1520,66,38,172,1596,109,123,125
3184,91352,"Census Tract 1021.05, Los Angeles County, Cali...",1597,841,60,6,39,756,17,17,25
3185,91504,"Census Tract 1021.05, Los Angeles County, Cali...",1597,841,60,6,39,756,17,17,25
3186,91505,"Census Tract 1021.05, Los Angeles County, Cali...",1597,841,60,6,39,756,17,17,25
2604,91040,"Census Tract 1021.07, Los Angeles County, Cali...",3356,1790,232,58,159,1566,121,59,257
2605,91352,"Census Tract 1021.07, Los Angeles County, Cali...",3356,1790,232,58,159,1566,121,59,257
2595,91040,"Census Tract 1031.01, Los Angeles County, Cali...",2320,1232,33,66,88,1088,33,42,105
2596,91042,"Census Tract 1031.01, Los Angeles County, Cali...",2320,1232,33,66,88,1088,33,42,105
2610,91040,"Census Tract 1031.02, Los Angeles County, Cali...",4167,1796,72,34,143,2371,119,86,171
2611,91042,"Census Tract 1031.02, Los Angeles County, Cali...",4167,1796,72,34,143,2371,119,86,171
2612,91040,"Census Tract 1032, Los Angeles County, California",5431,3107,179,70,245,2324,271,118,299
2613,91041,"Census Tract 1032, Los Angeles County, California",5431,3107,179,70,245,2324,271,118,299
2614,91342,"Census Tract 1032, Los Angeles County, California",5431,3107,179,70,245,2324,271,118,299
2606,91040,"Census Tract 1033, Los Angeles County, California",2854,1355,111,87,135,1499,67,98,96
2607,91352,"Census Tract 1033, Los Angeles County, California",2854,1355,111,87,135,1499,67,98,96
2597,91040,"Census Tract 1034, Los Angeles County, California",5661,2694,119,87,139,2967,245,110,201
2598,91042,"Census Tract 1034, Los Angeles County, California",5661,2694,119,87,139,2967,245,110,201
3085,91342,"Census Tract 1041.03, Los Angeles County, Cali...",3148,1532,49,53,78,1616,84,47,152
3023,91331,"Census Tract 1041.05, Los Angeles County, Cali...",4322,2053,55,61,101,2269,101,100,104
...,...,...,...,...,...,...,...,...,...,...,...
4171,92647,"Census Tract 996.02, Orange County, California",2710,1268,43,22,93,1442,68,60,175
4172,92683,"Census Tract 996.02, Orange County, California",2710,1268,43,22,93,1442,68,60,175
4181,92647,"Census Tract 996.03, Orange County, California",5586,2654,115,116,177,2932,204,121,314
4182,92649,"Census Tract 996.03, Orange County, California",5586,2654,115,116,177,2932,204,121,314
4183,92683,"Census Tract 996.03, Orange County, California",5586,2654,115,116,177,2932,204,121,314
4176,92647,"Census Tract 996.04, Orange County, California",3064,1479,82,32,131,1585,71,77,179
4177,92649,"Census Tract 996.04, Orange County, California",3064,1479,82,32,131,1585,71,77,179
3987,92605,"Census Tract 996.05, Orange County, California",2974,1455,129,72,119,1519,68,85,167
3988,92647,"Census Tract 996.05, Orange County, California",2974,1455,129,72,119,1519,68,85,167
4220,92655,"Census Tract 997.01, Orange County, California",5324,2602,121,117,182,2722,179,196,186
4221,92683,"Census Tract 997.01, Orange County, California",5324,2602,121,117,182,2722,179,196,186
4173,92647,"Census Tract 997.02, Orange County, California",6787,3563,160,169,139,3224,101,119,360
4174,92655,"Census Tract 997.02, Orange County, California",6787,3563,160,169,139,3224,101,119,360
4175,92683,"Census Tract 997.02, Orange County, California",6787,3563,160,169,139,3224,101,119,360
4178,92647,"Census Tract 997.03, Orange County, California",4517,2356,133,122,192,2161,235,89,166
4179,92655,"Census Tract 997.03, Orange County, California",4517,2356,133,122,192,2161,235,89,166
4180,92683,"Census Tract 997.03, Orange County, California",4517,2356,133,122,192,2161,235,89,166
4320,92683,"Census Tract 998.01, Orange County, California",4888,2460,92,88,199,2428,82,42,178
4321,92841,"Census Tract 998.01, Orange County, California",4888,2460,92,88,199,2428,82,42,178
4322,92844,"Census Tract 998.01, Orange County, California",4888,2460,92,88,199,2428,82,42,178
4327,92683,"Census Tract 998.02, Orange County, California",4235,2004,94,114,238,2231,105,122,300
4316,92683,"Census Tract 998.03, Orange County, California",4480,2334,105,129,221,2146,127,121,305
4309,92683,"Census Tract 999.02, Orange County, California",3740,1752,20,74,94,1988,66,30,162
4310,92683,"Census Tract 999.03, Orange County, California",4738,2516,97,59,119,2222,100,55,149
4311,92841,"Census Tract 999.03, Orange County, California",4738,2516,97,59,119,2222,100,55,149
4337,92683,"Census Tract 999.04, Orange County, California",5389,2639,142,94,148,2750,152,72,222
4338,92684,"Census Tract 999.04, Orange County, California",5389,2639,142,94,148,2750,152,72,222
4318,92683,"Census Tract 999.05, Orange County, California",3505,1776,50,48,102,1729,82,56,136
4319,92845,"Census Tract 999.05, Orange County, California",3505,1776,50,48,102,1729,82,56,136
4328,92683,"Census Tract 999.06, Orange County, California",4042,1951,133,82,212,2091,195,94,211

In [521]:
df_final[' Male: Age: 65 and over']=df_final[df_final.columns[4]]+df_final[df_final.columns[5]]+df_final[df_final.columns[6]]
df_final[' Female: Age: 65 and over']=df_final[df_final.columns[8]]+df_final[df_final.columns[9]]+df_final[df_final.columns[10]]
df_final[' Overall People Age: 65 and over']=df_final[df_final.columns[11]]+df_final[df_final.columns[12]]

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [522]:
df_final

,ZIP,Geography,Estimate; Total:,Estimate; Male:,Estimate; Male: - 65 to 69 years:,Estimate; Male: - 70 to 74 years:,Estimate; Male: - 75 years and over:,Estimate; Female:,Estimate; Female: - 65 to 69 years:,Estimate; Female: - 70 to 74 years:,Estimate; Female: - 75 years and over:,Male: Age: 65 and over,Female: Age: 65 and over,Overall People Age: 65 and over
2621,91042,"Census Tract 1011.10, Los Angeles County, Cali...",3924,1925,87,25,145,1999,156,67,168,257,391,648
2620,91042,"Census Tract 1011.22, Los Angeles County, Cali...",2797,1407,61,113,66,1390,140,65,64,240,269,509
2617,91042,"Census Tract 1012.10, Los Angeles County, Cali...",4931,2541,26,0,102,2390,215,55,117,128,387,515
2618,91043,"Census Tract 1012.10, Los Angeles County, Cali...",4931,2541,26,0,102,2390,215,55,117,128,387,515
2619,91042,"Census Tract 1012.20, Los Angeles County, Cali...",2356,1055,73,36,47,1301,22,40,125,156,187,343
2622,91042,"Census Tract 1013, Los Angeles County, California",3856,1865,106,134,170,1991,127,181,171,410,479,889
2623,91214,"Census Tract 1013, Los Angeles County, California",3856,1865,106,134,170,1991,127,181,171,410,479,889
2608,91040,"Census Tract 1014, Los Angeles County, California",3477,1679,84,90,56,1798,157,68,160,230,385,615
2609,91042,"Census Tract 1014, Los Angeles County, California",3477,1679,84,90,56,1798,157,68,160,230,385,615
3180,91352,"Census Tract 1021.03, Los Angeles County, Cali...",1618,745,67,37,60,873,33,44,66,164,143,307
3192,91352,"Census Tract 1021.04, Los Angeles County, Cali...",3116,1520,66,38,172,1596,109,123,125,276,357,633
3193,91504,"Census Tract 1021.04, Los Angeles County, Cali...",3116,1520,66,38,172,1596,109,123,125,276,357,633
3184,91352,"Census Tract 1021.05, Los Angeles County, Cali...",1597,841,60,6,39,756,17,17,25,105,59,164
3185,91504,"Census Tract 1021.05, Los Angeles County, Cali...",1597,841,60,6,39,756,17,17,25,105,59,164
3186,91505,"Census Tract 1021.05, Los Angeles County, Cali...",1597,841,60,6,39,756,17,17,25,105,59,164
2604,91040,"Census Tract 1021.07, Los Angeles County, Cali...",3356,1790,232,58,159,1566,121,59,257,449,437,886
2605,91352,"Census Tract 1021.07, Los Angeles County, Cali...",3356,1790,232,58,159,1566,121,59,257,449,437,886
2595,91040,"Census Tract 1031.01, Los Angeles County, Cali...",2320,1232,33,66,88,1088,33,42,105,187,180,367
2596,91042,"Census Tract 1031.01, Los Angeles County, Cali...",2320,1232,33,66,88,1088,33,42,105,187,180,367
2610,91040,"Census Tract 1031.02, Los Angeles County, Cali...",4167,1796,72,34,143,2371,119,86,171,249,376,625
2611,91042,"Census Tract 1031.02, Los Angeles County, Cali...",4167,1796,72,34,143,2371,119,86,171,249,376,625
2612,91040,"Census Tract 1032, Los Angeles County, California",5431,3107,179,70,245,2324,271,118,299,494,688,1182
2613,91041,"Census Tract 1032, Los Angeles County, California",5431,3107,179,70,245,2324,271,118,299,494,688,1182
2614,91342,"Census Tract 1032, Los Angeles County, California",5431,3107,179,70,245,2324,271,118,299,494,688,1182
2606,91040,"Census Tract 1033, Los Angeles County, California",2854,1355,111,87,135,1499,67,98,96,333,261,594
2607,91352,"Census Tract 1033, Los Angeles County, California",2854,1355,111,87,135,1499,67,98,96,333,261,594
2597,91040,"Census Tract 1034, Los Angeles County, California",5661,2694,119,87,139,2967,245,110,201,345,556,901
2598,91042,"Census Tract 1034, Los Angeles County, California",5661,2694,119,87,139,2967,245,110,201,345,556,901
3085,91342,"Census Tract 1041.03, Los Angeles County, Cali...",3148,1532,49,53,78,1616,84,47,152,180,283,463
3023,91331,"Census Tract 1041.05, Los Angeles County, Cali...",4322,2053,55,61,101,2269,101,100,104,217,305,522
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4171,92647,"Census Tract 996.02, Orange County, California",2710,1268,43,22,93,1442,68,60,175,158,303,461
4172,92683,"Census Tract 996.02, Orange County, California",2710,1268,43,22,93,1442,68,60,175,158,303,461
4181,92647,"Census Tract 996.03, Orange County, California",5586,2654,115,116,177,2932,204,121,314,408,639,1047
4182,92649,"Census Tract 996.03, Orange County, California",5586,2654,115,116,177,2932,204,121,314,408,639,1047
4183,92683,"Census Tract 996.03, Orange County, California",5586,2654,115,116,177,2932,204,121,314,408,639,1047
4176,92647,"Census Tract 996.04, Orange County, California",3064,1479,82,32,131,1585,71,77,179,245,327,572
4177,92649,"Census Tract 996.04, Orange County, California",3064,1479,82,32,131,1585,71,77,179,245,327,572
3987,92605,"Census Tract 996.05, Orange County, California",2974,1455,129,72,119,1519,68,85,167,320,320,640
3988,92647,"Census Tract 996.05, Orange County, California",2974,1455,129,72,119,1519,68,85,167,320,320,640
4220,92655,"Census Tract 997.01, Orange County, California",5324,2602,121,117,182,2722,179,196,186,420,561,981
4221,92683,"Census Tract 997.01, Orange County, California",5324,2602,121,117,182,2722,179,196,186,420,561,981
4173,92647,"Census Tract 997.02, Orange County, California",6787,3563,160,169,139,3224,101,119,360,468,580,1048
4174,92655,"Census Tract 997.02, Orange County, California",6787,3563,160,169,139,3224,101,119,360,468,580,1048
4175,92683,"Census Tract 997.02, Orange County, California",6787,3563,160,169,139,3224,101,119,360,468,580,1048
4178,92647,"Census Tract 997.03, Orange County, California",4517,2356,133,122,192,2161,235,89,166,447,490,937
4179,92655,"Census Tract 997.03, Orange County, California",4517,2356,133,122,192,2161,235,89,166,447,490,937
4180,92683,"Census Tract 997.03, Orange County, California",4517,2356,133,122,192,2161,235,89,166,447,490,937
4320,92683,"Census Tract 998.01, Orange County, California",4888,2460,92,88,199,2428,82,42,178,379,302,681
4321,92841,"Census Tract 998.01, Orange County, California",4888,2460,92,88,199,2428,82,42,178,379,302,681
4322,92844,"Census Tract 998.01, Orange County, California",4888,2460,92,88,199,2428,82,42,178,379,302,681
4327,92683,"Census Tract 998.02, Orange County, California",4235,2004,94,114,238,2231,105,122,300,446,527,973
4316,92683,"Census Tract 998.03, Orange County, California",4480,2334,105,129,221,2146,127,121,305,455,553,1008
4309,92683,"Census Tract 999.02, Orange County, California",3740,1752,20,74,94,1988,66,30,162,188,258,446
4310,92683,"Census Tract 999.03, Orange County, California",4738,2516,97,59,119,2222,100,55,149,275,304,579
4311,92841,"Census Tract 999.03, Orange County, California",4738,2516,97,59,119,2222,100,55,149,275,304,579
4337,92683,"Census Tract 999.04, Orange County, California",5389,2639,142,94,148,2750,152,72,222,384,446,830
4338,92684,"Census Tract 999.04, Orange County, California",5389,2639,142,94,148,2750,152,72,222,384,446,830
4318,92683,"Census Tract 999.05, Orange County, California",3505,1776,50,48,102,1729,82,56,136,200,274,474
4319,92845,"Census Tract 999.05, Orange County, California",3505,1776,50,48,102,1729,82,56,136,200,274,474
4328,92683,"Census Tract 999.06, Orange County, California",4042,1951,133,82,212,2091,195,94,211,427,500,927

In [523]:
df_orange=df_final[df_final['Geography'].str.contains('Orange')]

In [524]:
df_la=df_final[df_final['Geography'].str.contains('Los')]

In [525]:
len(df_la)

3954

In [526]:
len(df_orange)

1008

In [527]:
len(df_final)==len(df_la)+len(df_orange)

True

In [528]:
df_la=df_la.groupby(['ZIP']).sum()

In [529]:
df_la

,Estimate; Total:,Estimate; Male:,Estimate; Male: - 65 to 69 years:,Estimate; Male: - 70 to 74 years:,Estimate; Male: - 75 years and over:,Estimate; Female:,Estimate; Female: - 65 to 69 years:,Estimate; Female: - 70 to 74 years:,Estimate; Female: - 75 years and over:,Male: Age: 65 and over,Female: Age: 65 and over,Overall People Age: 65 and over
ZIP,,,,,,,,,,,,
90001,57702,28712,830,528,846,28990,1042,748,1066,2204,2856,5060
90002,51816,24237,699,546,539,27579,911,656,1113,1784,2680,4464
90003,103994,49282,1678,1024,1544,54712,1657,1270,2257,4246,5184,9430
90004,67407,33789,1258,859,1418,33618,1559,1186,1991,3535,4736,8271
90005,66270,32796,1276,1086,1273,33474,1669,1336,2215,3635,5220,8855
90006,79185,40868,1565,1217,1112,38317,1691,1320,2265,3894,5276,9170
90007,69546,33863,839,490,881,35683,1067,632,1785,2210,3484,5694
90008,43573,18880,917,759,1691,24693,1517,1266,2654,3367,5437,8804
90009,0,0,0,0,0,0,0,0,0,0,0,0
90010,42779,20710,819,580,886,22069,1015,912,1378,2285,3305,5590
90011,88324,44319,926,578,1016,44005,1215,767,1643,2520,3625,6145
90012,48963,28618,1043,602,1430,20345,1098,673,2246,3075,4017,7092
90013,25529,15275,753,296,925,10254,426,315,1414,1974,2155,4129
90014,18366,11692,547,187,389,6674,191,197,369,1123,757,1880
90015,40864,21651,693,502,814,19213,745,463,1541,2009,2749,4758
90016,77134,35975,1408,974,1871,41159,2200,1675,3197,4253,7072,11325
90017,39453,20854,485,407,711,18599,519,687,1440,1603,2646,4249
90018,71674,33737,1389,918,1446,37937,1655,1273,2981,3753,5909,9662
90019,80277,39432,1817,1103,1755,40845,1929,1586,2894,4675,6409,11084
90020,66599,32640,1247,595,1453,33959,1468,1105,2051,3295,4624,7919
90021,11306,7451,444,98,257,3855,146,8,129,799,283,1082
90022,75633,36560,1249,1051,2269,39073,1854,1682,3264,4569,6800,11369
90023,56982,29011,945,755,1257,27971,1252,786,1675,2957,3713,6670
90024,52565,25281,654,691,1570,27284,930,545,2229,2915,3704,6619
90025,69980,34049,1489,1038,2019,35931,1868,1457,2977,4546,6302,10848
90026,82143,41335,1619,1143,1787,40808,1826,1408,2868,4549,6102,10651
90027,62143,30910,1431,1084,1596,31233,1639,1258,2706,4111,5603,9714
90028,62188,33878,920,654,1330,28310,1276,1010,1905,2904,4191,7095
90029,72575,36885,1604,1053,1420,35690,1697,1186,2761,4077,5644,9721
90030,1827,821,95,26,54,1006,131,15,135,175,281,456
...,...,...,...,...,...,...,...,...,...,...,...,...
91780,47879,22675,1254,722,1891,25204,1612,1320,2641,3867,5573,9440
91786,3949,1823,4,0,4,2126,4,0,10,8,14,22
91788,3063,1391,65,52,70,1672,76,92,140,187,308,495
91789,57462,27937,1845,1128,1552,29525,2051,1384,2184,4525,5619,10144
91790,58402,28406,1225,922,1779,29996,1531,1062,2659,3926,5252,9178
91791,48264,23550,1104,917,1705,24714,1359,724,2728,3726,4811,8537
91792,39058,18866,1109,672,910,20192,1343,777,1296,2691,3416,6107
91793,5024,2385,107,56,138,2639,174,123,236,301,533,834
91801,59115,28304,1187,965,1729,30811,1597,1391,2974,3881,5962,9843
91802,3434,1577,182,56,201,1857,18,50,475,439,543,982
91803,42598,21047,1157,858,1618,21551,1322,924,2316,3633,4562,8195
93063,3296,1584,175,104,129,1712,228,108,177,408,513,921
93243,1084,560,48,35,54,524,41,25,23,137,89,226
93510,10558,5631,348,398,181,4927,399,205,332,927,936,1863
93532,9662,4965,306,154,249,4697,211,147,303,709,661,1370
93534,65401,31155,1453,1219,1538,34246,1883,1144,2378,4210,5405,9615
93535,55343,25914,880,1043,979,29429,1346,816,1271,2902,3433,6335
93536,67921,35966,1475,1067,1493,31955,1667,1221,2236,4035,5124,9159
93539,2971,1438,57,69,97,1533,57,48,174,223,279,502
93543,19672,9665,448,355,548,10007,603,436,619,1351,1658,3009
93544,8626,4411,369,281,312,4215,327,280,337,962,944,1906
93550,66292,32220,982,834,1305,34072,1257,969,1911,3121,4137,7258
93551,54153,26486,1275,760,1359,27667,1418,1069,1911,3394,4398,7792
93552,40133,19925,792,488,690,20208,896,712,964,1970,2572,4542
93553,9861,4993,281,265,373,4868,338,223,380,919,941,1860
93560,3059,1600,107,54,103,1459,86,67,166,264,319,583
93563,4303,2191,138,199,201,2112,134,157,260,538,551,1089
93586,3829,1778,54,27,105,2051,53,101,145,186,299,485
93591,19251,9666,636,418,466,9585,664,451,561,1520,1676,3196
93599,11,11,0,0,0,0,0,0,0,0,0,0

In [530]:
df_orange=df_orange.groupby(['ZIP']).sum()

In [531]:
df_orange

,Estimate; Total:,Estimate; Male:,Estimate; Male: - 65 to 69 years:,Estimate; Male: - 70 to 74 years:,Estimate; Male: - 75 years and over:,Estimate; Female:,Estimate; Female: - 65 to 69 years:,Estimate; Female: - 70 to 74 years:,Estimate; Female: - 75 years and over:,Male: Age: 65 and over,Female: Age: 65 and over,Overall People Age: 65 and over
ZIP,,,,,,,,,,,,
90620,64149,31496,1680,1169,1755,32653,1950,1333,2542,4604,5825,10429
90621,38973,19232,828,564,840,19741,851,492,1133,2232,2476,4708
90622,3987,2061,63,125,162,1926,71,84,137,350,292,642
90623,26584,12861,735,699,695,13723,973,606,1203,2129,2782,4911
90630,61796,29927,1534,940,2313,31869,1985,1380,3062,4787,6427,11214
90631,67832,32474,1317,1231,2449,35358,1693,1700,3754,4997,7147,12144
90632,2988,1412,75,54,260,1576,108,192,219,389,519,908
90633,3111,1579,20,104,88,1532,38,13,96,212,147,359
90638,12929,6566,330,244,437,6363,167,279,396,1011,842,1853
90680,42099,20464,822,757,865,21635,1166,683,1677,2444,3526,5970
90720,25436,12128,668,515,1189,13308,833,543,1519,2372,2895,5267
90721,2393,1202,37,65,105,1191,56,64,197,207,317,524
90740,30080,13780,1117,1016,2458,16300,1233,1202,4156,4591,6591,11182
90742,915,495,59,47,72,420,56,21,30,178,107,285
90743,915,495,59,47,72,420,56,21,30,178,107,285
90808,2393,1202,37,65,105,1191,56,64,197,207,317,524
92602,37740,17884,907,377,401,19856,947,419,949,1685,2315,4000
92603,20863,9982,777,482,534,10881,858,352,685,1793,1895,3688
92604,38068,18096,859,825,1164,19972,1291,1087,1996,2848,4374,7222
92605,2974,1455,129,72,119,1519,68,85,167,320,320,640
92606,32069,15061,326,458,397,17008,595,670,843,1181,2108,3289
92607,2744,1361,169,86,86,1383,132,46,67,341,245,586
92609,4110,2221,46,56,119,1889,101,133,152,221,386,607
92610,15271,7202,337,130,124,8069,298,154,198,591,650,1241
92612,29220,14907,473,478,793,14313,805,591,1191,1744,2587,4331
92614,35248,16552,449,605,606,18696,911,665,1058,1660,2634,4294
92615,3115,1423,138,61,85,1692,161,75,177,284,413,697
92616,3290,1352,15,27,197,1938,108,58,450,239,616,855
92617,15613,7105,65,38,98,8508,51,31,50,201,132,333
92618,54739,27363,1164,663,1247,27376,1310,762,1620,3074,3692,6766
...,...,...,...,...,...,...,...,...,...,...,...,...
92832,39446,19656,737,581,1409,19790,1082,667,1833,2727,3582,6309
92833,55680,27672,1137,916,1919,28008,1374,1205,2400,3972,4979,8951
92834,5131,2586,32,77,197,2545,139,43,272,306,454,760
92835,61082,29212,1299,1034,2620,31870,1985,1155,3590,4953,6730,11683
92836,4248,2126,66,7,211,2122,56,103,196,284,355,639
92837,5293,3019,145,30,140,2274,115,90,250,315,455,770
92838,3217,1515,100,95,324,1702,157,75,422,519,654,1173
92840,75647,37569,1845,1250,1716,38078,1707,1419,3037,4811,6163,10974
92841,58900,29309,1377,1273,1434,29591,1713,992,2415,4084,5120,9204
92842,4780,2319,119,109,83,2461,84,149,140,311,373,684
92843,82340,40700,1863,1335,2072,41640,2049,1738,3042,5270,6829,12099
92844,45167,21982,1098,742,1159,23185,1011,924,1670,2999,3605,6604
92845,20490,9990,420,488,878,10500,676,506,1106,1786,2288,4074
92846,3483,1597,56,72,73,1886,120,69,144,201,333,534
92856,3505,1690,57,76,32,1815,81,12,81,165,174,339
92857,6009,2829,86,91,80,3180,113,162,167,257,442,699
92859,3062,1479,74,27,37,1583,108,47,51,138,206,344
92861,14416,7307,348,461,680,7109,461,370,698,1489,1529,3018
92863,3837,1894,119,98,125,1943,96,100,261,342,457,799
92865,35308,17450,716,530,873,17858,742,615,1252,2119,2609,4728
92866,17208,8079,364,206,300,9129,429,200,712,870,1341,2211
92867,61392,30208,1586,1347,1823,31184,1718,1166,2538,4756,5422,10178
92868,39683,21879,734,533,621,17804,753,379,1283,1888,2415,4303
92869,40590,19967,1099,1173,1251,20623,1341,1091,1786,3523,4218,7741
92870,68083,32821,1635,1110,1892,35262,1961,1302,3181,4637,6444,11081
92871,6457,3235,65,35,72,3222,21,80,233,172,334,506
92885,5596,2788,315,108,234,2808,339,69,452,657,860,1517
92886,62636,30413,2248,1353,1970,32223,2086,1449,2684,5571,6219,11790
92887,23271,11323,745,516,481,11948,670,433,671,1742,1774,3516
92899,67,35,0,7,0,32,4,0,0,7,4,11

In [ ]:
# Export to csv file

In [532]:
df_la.to_csv('age_la.csv', sep='\t')

In [533]:
df_orange.to_csv('age_orange.csv', sep='\t')